[2023-03-03 06:39:20] [ERROR  ] root: Could not set up PostgreSQL. Exiting.
Traceback (most recent call last):
  File "main.py", line 29, in run_bot
    pool = await create_pool()
  File "main.py", line 18, in create_pool
    return await asyncpg.create_pool(
TypeError: create_pool() argument after ** must be a mapping, not str
[2023-03-03 06:40:40] [ERROR  ] root: Could not set up PostgreSQL. Exiting.
Traceback (most recent call last):
  File "main.py", line 29, in run_bot
    pool = await create_pool()
  File "main.py", line 18, in create_pool
    return await asyncpg.create_pool(
TypeError: create_pool() argument after ** must be a mapping, not str
